// <auto-generated/>

using System;

namespace DimonSmart
{
    [AttributeUsage(
        AttributeTargets.Class |
        AttributeTargets.Method |
        AttributeTargets.Property |
        AttributeTargets.Constructor,
        Inherited = true,
        AllowMultiple = false)]
    public sealed class DimonSmartAllowDynamicLeakAttribute : Attribute
    {
    }
}
